apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: catalogue-service
  namespace: sock-shop-v8
  labels:
    name: catalogue
spec:
  workload:
    apiVersion: v1
    kind: Service
    metadata:
      name: catalogue
      namespace: sock-shop-v8
      labels:
        name: catalogue
    spec:  
      hosts:
      - catalogue
        http:
      - fault:
        abort:
          httpStatus: 500
          percent: 100
      route:
      - destination:
          host: catalogue
          subset: v1
